# Generated by Django 4.0.5 on 2022-07-11 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_created=True, default=datetime.datetime(2022, 7, 11, 10, 16, 12, 995855))),
                ('content', models.CharField(max_length=2048)),
                ('deadline', models.DateTimeField(default=datetime.datetime(2022, 8, 10, 10, 16, 12, 995878))),
                ('done', models.BooleanField(default=False)),
                ('tag', models.ManyToManyField(related_name='tags', to='todo_list.tag')),
            ],
        ),
    ]
