# Generated by Django 4.0.5 on 2022-07-11 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='datetime',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2022, 7, 11, 10, 16, 40, 89005)),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 10, 10, 16, 40, 89030)),
        ),
    ]
